#!/bin/bash
if [ "$#" -ne 1 ]; then
    echo "Illegal number of parameters"
	exit 0
fi
mkdir "/mnt/magneto/videoclub/Series/$1"
cd "/mnt/magneto/videoclub/Series/$1"
echo "$1" > "$1.txt"
echo "folder create in /mnt/magneto/videoclub/Series/$1"
